---
include:

  - board: ergohaven
    shield: k04_left
  - board: ergohaven
    shield: k04_right
    keymap: k04_ruen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: k04_right_ruen-ergohaven-zmk
  - board: ergohaven
    shield: k04_right k04_right_touch
    keymap: k04
    snippet: studio-rpc-usb-uart
    artifact-name: k04_right_touch
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: ergohaven
    shield: k04_right k04_right_ball
    keymap: k04
    snippet: studio-rpc-usb-uart
    artifact-name: k04_right_ball
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: ergohaven
    shield: k04_qube qube dongle_screen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: k04_qube-ergohaven-zmk
  - board: ergohaven
    shield: k04_qube qube dongle_screen
    keymap: k04_ruen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: k04_qube_ruen-ergohaven-zmk
  - board: ergohaven
    shield: k04_right_qube
