name: Release Binaries

on:
  push:
    tags:
      - '*'

jobs:

  build:
    uses: ./.github/workflows/build.yml

  pre-release:
    name: Pre-Release
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      packages: 'write'
      pull-requests: 'read'

  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          path: firmware

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
