name: Release Binaries

on:
  push:
    tags:
      - '*'

jobs:

  build:
    uses: ./.github/workflows/build.yml

  release:
    name: Release
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      packages: 'write'
      pull-requests: 'read'

    steps:
      - name: Download
        uses: actions/download-artifact@v4
        with:
          path: firmware

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          files: |
            firmware/**/*.uf2
